### ISSUE TITLE
Licensing for old resource versions now that they are deleted from GitHub

### ISSUE THREAD

**Issue by lfuelling** [Playlolly/playlolly_tesla#2]
Hi,

after you made the rather ♡♡♡♡ move of deleting the repos and paywalling them, what am I supposed to do with the old resource versions still running on servers I operate?

The resources themselves were free to use previously but are all rights reserved according to the readme; should I delete them?

**Comment by boostvolt** [comment]
The resources are still on GitHub simply private and no longer visible to the public. To comply with copyright regulations, you must delete the existing resources. You can at any time buy our [current version](https://playlolly.vercel.app) for a small amount of money and use it on your server. Unfortunately, due to the FiveM licensing fees, we can no longer freely distribute the resources without making financial loss. 

According to FiveM, further use would also be a direct violation of the FiveM ToS which can lead to the server being permanently banned.
